### ISSUE TITLE
Any pointers to help me set my picture?

### ISSUE THREAD

**Issue by brody2consult** [dbtek/paper#1]
First, I would like to thank you for publishing this project! I found your project at jekyllthemes.org and have already started using it for what will be my new blog and homepage at www.brodybits.com.

Unfortunately Jekyll and Material Design Lite are both very new for me even though I did look at them in the past. The tutorials that I have found so far cover creating a blog from scratch (which is not needed for this theme) or creating a blog from another template (such as Poole).

I am having trouble figuring out how to change my photo, any pointers would really help.

I think this project definitely needs a tutorial. I am happy to contribute as I figure out how to do the customizations and start writing blog posts.

I will also try to import some of my old Blogger postings, will post my results.

**Comment by dbtek** [comment]
Hi @brodybits. Thanks for pointing out the tutorial need. I guess you figured out avatar config (by md5 hash & gravatar), right?

**Comment by dbtek** [comment]
Sorry, I was wrong. You should not change the `src` attribute of `img` tag. Just update the `email_md5` property in `_config.yml` with md5 hash of your email address (which is used to fetch matching gravatar image).
See [gravatar.com](http://gravatar.com/support/what-is-gravatar) if you're not familiar.

**Comment by brody2consult** [comment]
Thanks. I am actually not using gravator.com, just using a static image instead.
