### ISSUE TITLE
jekyll 3.2.1 | Error:  The blue-pink theme could not be found.

### ISSUE THREAD

**Issue by nzw0301** [dbtek/paper#5]
when I update jekyll to 3.2.1, page's build fails.

```
$ bundle exec jekyll server
Configuration file: /path_to/paper/_config.yml
jekyll 3.2.1 | Error:  The blue-pink theme could not be found.
```

**Comment by nzw0301** [comment]
solved it

**Comment by thobianchi** [comment]
How?!? I get the same error...

**Comment by nzw0301** [comment]
@thobianchi 
1. remove [this line](https://github.com/dbtek/paper/blob/bda617ba2c38bd3d0441509fd8480ec6a12f71cb/_config.yml#L29)
2. change `<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.{{ site.theme }}.min.css">` to  `<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.blue-pink.min.css">` in https://github.com/dbtek/paper/blob/master/_includes/head.html#L9
